[package]
name = "snapshot_restore"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-config = "1.6.1"
aws-sdk-ec2 = "1.121.1"
clap = { version = "4.5.36", features = ["derive"] }
config = "0.15.11"
futures = "0.3.31"
inquire = "0.7.5"
tokio = { version = "1.44.2", features = ["full"] }
